Updated the Skeleton
FEC-Team-JOJO/FEC pull request #2
Opened 2022-03-31 17:28 UTC by alexshiao99

2022-03-31 18:03 UTC, ceads1618 requested changes
This is a useless chunk of code that doesn't run

2022-03-31 18:05 UTC, alexshiao99 commented on client/src/Components/Reviews/index.jsx
Obvious typo for 'fom'

2022-03-31 18:06 UTC, AdarshrajRav reviewed
check

2022-03-31 18:06 UTC, AdarshrajRav commented on client/src/Components/Reviews/index.jsx
> +import React fom 'react';
hi

2022-03-31 18:06 UTC, AdarshrajRav commented on client/src/Components/Reviews/index.jsx
hi

2022-03-31 18:09 UTC, ceads1618 commented on client/src/Components/App.jsx
> -    <Overview />
Please review lines 13 through 17 for appropriate indentations.

2022-03-31 18:11 UTC, ceads1618 requested changes
Please review the three comments I made regarding your code.

2022-03-31 18:11 UTC, ceads1618 commented on client/src/Components/App.jsx
> +    <QA />;
This is just a single comment

2022-03-31 18:11 UTC, ceads1618 commented on client/src/Components/App.jsx
> +hereis useless code that wont run
This is another test

2022-03-31 18:11 UTC, ceads1618 commented on client/src/Components/App.jsx
> +hereis useless code that wont run
Lastly checking to see how this format appears

2022-03-31 18:14 UTC, ceads1618 approved these changes, later dismissed
Looks good to go!

2022-03-31 18:17 UTC, AdarshrajRav approved these changes
Looks great!

2022-03-31 18:17 UTC, merged

2022-04-01 01:42 UTC, euniceyunjkim reviewed
Update: great job correcting the errors! 

Please review the typo - should be "from".